name: Protections

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn dev:prepare
      - name: Lint
        run: yarn lint:ci
      - name: Typecheck
        run: yarn test:types
      - name: Verify commits
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose
