name: Protections

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint:ci
        
      - name: Verify commits
        run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Pack
        run: pnpm pack

      - uses: actions/upload-artifact@v4
        with:
          name: nuxt-mock-server-${{ github.sha }}.tgz
          path: nuxt-mock-server-*.tgz
          if-no-files-found: "error"
          retention-days: 30

