name: Release

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint:ci
      - name: Prepare
        run: yarn build:prepare
      - name: Build
        run: yarn build:prepack
      - name: Release
        run: yarn semantic-release